### ISSUE TITLE
Warning dotyczący `dbFetch()` w `pobierz_wyniki_egzaminu()` 

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#11]
Przy wywołaniu funkcji `pobierz_wyniki_egzaminu()` , np. `pobierz_wyniki_egzaminu(polacz(), 'matura', 'fizyka rozszerzona', 2017, TRUE)` pojawia się ostrzeżenie o treści:

Warning in result_fetch(res@ptr, n = n) :
  Don't need to call dbFetch() for statements, only for queries

**Comment by tzoltak** [comment]
Nie chciałbym być uznany za natręta, ale w wersji 1.7.2 wciąż jeszcze mi się te ostrzeżenia przy wywoływaniu `pobierz_wyniki_egzaminu()` pojawiają.

**Comment by zozlak** [comment]
Ech, moje domowe połączenie z netem nie pozwala mi sprawdzić funkcji pobierających większe ilości danych. Teraz powinno być ok (przy okazji wywaliłem obejścia błędów w RPostgreSQL)

**Comment by tzoltak** [comment]
Jak by co możesz próbować tego przykładu z fizyką - specjalnie wybrałem taki mało popularny przedmiot.

**Comment by tzoltak** [comment]
Niemniej potwierdzam, że już mi się nic nie pluje.
