### ISSUE TITLE
Jeszcze jedno dziwne ostrzeżenie

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#12]
Właściwie to chyba bardziej coś związanego z bazą, niż z pakietem ZPD, ale tu mogę Ci to wygodnie opisać.

W funkcji `pobierz_dane_kontekstowe()` pakietu EWDdane jest fragment, który służy do sprawdzenia poziomu uprawnień dostępu do bazy, z jakimi została wywołana:
`
try({
  tmp = tbl(src, sql("SELECT * FROM dane_osobowe.obserwacje LIMIT 1"))
  daneOsobowe = TRUE
}, silent = TRUE)
`

Jeśli `src` jest połączeniem mającym prawa dostępu do `dane_osobowe.obserwacje` efektem ubocznym wywołania jest jednak ostrzeżenie o treści:

Warning in result_create(conn@ptr, statement) :
  Unknown field type (20344) in column plec

W zasadzie nie przeszkadza to uzyskać pożądanego wyniku (i jak by co, zawsze mogę to wywołanie obłożyć `suppressWarnings()` ;) ) ale zastanawiam się, skąd się wzięło.

**Comment by zozlak** [comment]
Bierze się to z tego, że na poziomie bazy danych płeć jest zdefiniowana jako nowy typ danych (enumerowany o możliwych wartościach *m* lub *k*) a nie jako zwykły tekst z ograniczeniem klucza obcego do tablicy *słownikowej* z *k* i *m* jako rekordami danych.

Oczywiście RPostgres (ani żaden inny pakiet) nie zna tego nowego typu danych, więc odczytuje go jako zwykły tekst, co jest zresztą oczekiwanym działaniem. Tyle że emituje jeszcze ostrzeżenie.

Dodam `suppressWarnings()` w bebechach.

**Comment by tzoltak** [comment]
Dobra, w pakiecie EWDdane to już ja grzebnę.

`pobierz_uczniow()` z pakietu ZPD już w obecnej wersji warningów nie zgłasza.
