### ISSUE TITLE
pobierz_wyniki_egzaminu() nie zwraca wszystkich testów, które powinna

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#14]
Przy wywołaniu funkcji `pobierz_wyniki_egzaminu() ` w odniesieniu do części matury, do której przypisane były dwa testy (np. matematyka podstawowa, czy angielski) zwróciła ona wyniki tylko jednego. Przykładowo wywołanie: `pobierz_wyniki_egzaminu(polacz(), 'matura', 'j. angielski rozszerzona', 2017, TRUE) %>% collect(n = Inf)` (angielski rozszerzony żeby to było relatywnie mało ludzi) zwraca wyniki tylko testu o `id_testu` równym 1817, choć powinno zwracać również wyniki testu o id 1793.

Biorąc pod uwagę, jak wygląda funkcja `pobierz_wyniki_egzaminu() `, problem dotyczy chyba funkcji wbudowanej w bazę `zbuduj_widok_czesci_egzaminu()`.

**Comment by zozlak** [comment]
W rzeczy samej w funkcji wbudowanej w bazę był paskudny babol.
Teraz powinno działać.
