### ISSUE TITLE
Problem z instalacja ZPD

### ISSUE THREAD

**Issue by dax44** [zozlak/ZPD#15]
Podczas instalacji ze źródła pakietu ZPD pakiet RPostgres w versji 0.1-7 próbuje się instalować (nieskutecznie)

`R> devtools::install_github("zozlak/ZPD")
Downloading GitHub repo zozlak/ZPD@master
These packages have more recent versions available.
Which would you like to update?

1:   RPostgres (1.1.1 -> 8488b4a4d...) [GitHub]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
RPostgres (1.1.1 -> 8488b4a4d...) [GitHub]
Downloading GitHub repo r-dbi/RPostgres@v0.1-7
√  checking for file 'C:\Users\majer\AppData\Local\Temp\RtmpMb3T0s\remotes2dd82eab6542\r-dbi-RPostgres-2343b2e/DESCRIPTION' (434ms)
-  preparing 'RPostgres': (376ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RPostgres_0.1-7.tar.gz'
   Ostrzeżenie: file 'RPostgres/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/majer/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Hi Dax, welcome to R
* installing *source* package 'RPostgres' ...
** using staged installation
** libs

*** arch - i386
rm -f PqConnection.o PqResult.o PqRow.o PqUtils.o RPostgres-init.o RcppExports.o connection.o encode.o encrypt.o result.o RPostgres.dll
"C:/PROGRA~1/R/R-36~1.0/bin/i386/Rscript.exe" "../tools/winlibs.R"
Hi Dax, welcome to R
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../windows/libpq-9.5.2/include -I"C:/Users/majer/Documents/R/win-library/3.6/BH/include" -I"C:/Users/majer/Documents/R/win-library/3.6/plogr/include" -I"C:/Users/majer/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c PqConnection.cpp -o PqConnection.o
PqConnection.cpp: In constructor 'PqConnection::PqConnection(std::vector<std::basic_string<char> >, std::vector<std::basic_string<char> >)':
PqConnection.cpp:18:26: error: 'setenv' was not declared in this scope
   setenv("PGTZ", "UTC", 1);
                          ^
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/i386/Makeconf:215: PqConnection.o] Error 1
ERROR: compilation failed for package 'RPostgres'
* removing 'C:/Users/majer/Documents/R/win-library/3.6/RPostgres'
* restoring previous 'C:/Users/majer/Documents/R/win-library/3.6/RPostgres'
Błąd w poleceniu 'file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)':
  (przetworzone z ostrzeżenia) problem z kopiowaniem C:\Users\majer\Documents\R\win-library\3.6\00LOCK-RPostgres\RPostgres\libs\x64\RPostgres.dll do C:\Users\majer\Documents\R\win-library\3.6\RPostgres\libs\x64\RPostgres.dll: Permission denied
* removing 'C:/Users/majer/Documents/R/win-library/3.6/RPostgres'
* restoring previous 'C:/Users/majer/Documents/R/win-library/3.6/RPostgres'
Błąd w poleceniu 'file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)':
  (przetworzone z ostrzeżenia) problem z kopiowaniem C:\Users\majer\Documents\R\win-library\3.6\00LOCK-RPostgres\RPostgres\libs\x64\RPostgres.dll do C:\Users\majer\Documents\R\win-library\3.6\RPostgres\libs\x64\RPostgres.dll: Permission denied
Wykonywanie wstrzymane
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/majer/AppData/Local/Temp/RtmpMb3T0s/file2dd8639c1f4e/RPostgres_0.1-7.tar.gz’ had non-zero exit status`

A jeśli zainstaluję RPostgres CRAN-owe to instalacja ZPD przebiega bez problemów, jednak jak się uruchomi pakiet, to nie działa ściąganie 

`library(tidyverse)
library(ZPD)

src = polacz()

dane = pobierz_wyniki_egzaminu(src = src, 'egzamin gimnazjalny', 'matematyka', 2012, TRUE) %>% 
    collect()`

Error: `con` must not be NULL

Pozdrawiam

**Comment by zozlak** [comment]
W pierwszej kwestii odsyłam do twórców pakietu RPostgres.

W drugiej kwestii nie umiem zreplikować problemu (tzn. u mnie kod poprawnie pobiera dane).
Ponieważ jednak komunikat błędu sugeruje problemy z nawiązywaniem połączenia z bazą danych, spróbujmy poeksperymentować w tym kierunku. Proszę spróbować wykonać:

```
DBI::dbGetQuery(src$con, "SELECT 1 AS test")
```
Co powinno zwrócić:
```
  test
1    1
```
Jeśli ten test się powiedzie, proszę spróbować pobrać jakąś małą grupę danych, np.:
```
pobierz_testy(src)
```
Jeśli i tu się uda, proszę spróbować z pierwszymi nastoma wierszami `pobierz_wyniki_egzaminu()`:
```
pobierz_wyniki_egzaminu(src = src, 'egzamin gimnazjalny', 'matematyka', 2012, TRUE)
```

**Comment by dax44** [comment]
Pierwsze dwie komendy działają i zwracają właściwe wartość.
Niestety 
`pobierz_wyniki_egzaminu(src = src, 'egzamin gimnazjalny', 'matematyka', 2012, TRUE)`
nie działa i zwraca błąd
`Error: `con` must not be NULL`

**Comment by zozlak** [comment]
Generalnie wygląda mi to na problemy z RPostgres... Proszę spróbować:

```
library(ZPD)
src = polacz()
query = "SELECT zbuduj_widok_czesci_egzaminu('test', 'egzamin gimnazjalny', 'matematyka', 2012, true, true, null, true, true);"
DBI::dbExecute(src$con, e(query))
DBI::dbGetQuery(src$con, e("SELECT * FROM test LIMIT 10"))
dplyr::tbl(src, dplyr::sql(e("SELECT * FROM test LIMIT 10")))
```

**Comment by zozlak** [comment]
Dziś i jutro baza danych, z której pakiet korzysta będzie migrowana, w związku z czym żadne dane się nie pobiorą (choć z drugiej strony nie powinny też wyskakiwać błędy). Dam znać, kiedy migracja się zakończy.

**Comment by zozlak** [comment]
Dogrzebałem się do źródła `Error: con must not be NULL`, którym okazała się być [wersja 1.4 pakietu dbplyr](https://cran.r-project.org/web/packages/dbplyr/news/news.html#dbplyr-1.4.0) wprowadzająca wymóg podawania parametru `con` dla funkcji `escape()`.

Proszę zainstalować ZPD ponownie i spróbować pobrać dane raz jeszcze.

**Comment by dax44** [comment]
Potwierdzam teraz działa.
Wielkie dzięki za pomoc!
