### ISSUE TITLE
Matematyka rozszerzona 2015

### ISSUE THREAD

**Issue by dax44** [zozlak/ZPD#16]
Witam
Korzystając z Pana pakietu ZPD zauważyłem, że nie działa mi jeden rocznik matury rozszerzonej z matematyki 2015. Inne roczniki działają a ten nie. Czy może robię coś nie tak?

`pobierz_wyniki_egzaminu(src, 
                                        rodzajEgzaminu = "matura",
                                        rokEgzaminu = 2015,
                                        czescEgzaminu = "matematyka rozszerzona",
                                        czyEwd = T)`
Z góry dziękuję za odpowiedź
Dariusz

**Comment by zozlak** [comment]
Czym objawia się niedziałanie? W szczególności, czy wyskakuje jakiś komunikat o błędzie?

**Comment by dax44** [comment]
Oto komunikat błędu

`Error in result_create(conn@ptr, statement) : 
  Failed to fetch row: BĹÄ„D:  kaĹĽde zapytanie UNION musi mieÄ‡ tÄ… samÄ… liczbÄ™ kolumn
LINE 1: ...  SELECT * FROM __t1572888300_531711 UNION SELECT * FROM __t...
                                                             ^
QUERY:  create temp view t1572888300_53171 as  SELECT * FROM __t1572888300_531711 UNION SELECT * FROM __t1572888300_531712
CONTEXT:  funkcja PL/pgSQL zbuduj_widok_czesci_egzaminu(text,text,text,date,boolean,boolean,integer,boolean,boolean), wiersz 23 w EXECUTE
funkcja PL/pgSQL zbuduj_widok_czesci_egzaminu(text,text,text,integer,boolean,boolean,integer,boolean,boolean), wiersz 11 w RETURN`

**Comment by zozlak** [comment]
To taki bug-niebug.

Dla 2015 roku mamy w bazie wyniku dwóch matur - w nowej i starej formule. Składają się one z zupełnie innych zadań i jako takie są z sobą niekompatybilne, a jako że funkcja `pobierz_wyniki_egzaminu()` nie pozwala na wybranie konkretnej formuły matury, to nie da się nią pobrać danych maturalnych z 2015 r.

Polecam odfiltrowanie stosownego testu za pomocą `pobierz_testy(src) %>% filter(czesc_egzaminu == 'matematyka rozszerzona' & rok == 2015)` (jak się okaże są dwa testy z różnymi kodami arkusza), a następnie pobranie danych poszczególnych formuł za pomocą `pobierz_wyniki_testu(src, {idTestu})`
