### ISSUE TITLE
Obsługa błędnej definicji skrótu przez sprawdz_skroty_skal()

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#2]
Jeśli w ciągu znaków definiujących skrót nie znajdzie się znak '|', to funkcja sprawdz_skroty_skal() sypie się błędem w linii 49 (co jest efektem nieplanowanego wyniku działania strsplit() w linii 44). Niestety komunikat błędu jest mało informatywny, a na dodatek sposób konstrukcji funkcji edytuj_skale(), która woła sprawdz_skroty_skal() - konkretnie zamknięcie wszystkiego w jednym wielkim tryCatch() - skutecznie utrudnia dowiedzenie się nawet tego, że jest to problem właśnie ze sprawdz_skroty_skal().

Przydałoby się sprawdzanie na początku sprawdz_skroty_skal() warunku, czy nie będące brakami danych elementy argumentu 'skroty' zawierają '|', a jak nie, to poplucie się informatywnym błędem.

**Comment by zozlak** [comment]
Poprawione w wersji 0.6.8 pakietu (2 listopada 2014 :) )
