### ISSUE TITLE
normalizuj() pluje ostrzeżeniem o nieznanej kolumnie

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#5]
Wywoływanie funkcji normalizuj powoduje wyskakiwanie ostrzeżenia:

Warning message:
Unknown column 'grupa' 

Podejrzewam, że jest to efekt tego, że w wierszu 58. zawężasz obiekt normy do tylko dwóch kolumn - i żadna z nich to nie 'grupa' - ale wiersz 72. masz napisany tak, jakby ta kolumna cały czas tam była.

**Comment by zozlak** [comment]
Wklej mi proszę kodziach do zreplikowania błędu, bo jakoś na przypadkowo generowanych przeze mnie przykładach nie chce się zreplikować.

**Comment by tzoltak** [comment]
normalizuj(data.frame(suma = 1:10), polacz(), "suma", 1323, 1, '')
