### ISSUE TITLE
Ograniczenia podczas pobierania danych

### ISSUE THREAD

**Issue by bkolasa** [zozlak/ZPD#6]
Dzień dobry.

Mam pytanie. Czy na bazie IBE nalożone są jakieś limity, który uniemożliwiają pobranie więcej niż 10000 rekordów? Chciałem potrenować na niej jako na fajnym źródle "dużych" danych. Zauważyłem jednak, że połaczenie gwałtownie przycina się i zawiesza, gdy zapytamie zwraca więcej niż 10000 wierszy. Na potwierdzenie tego 5000 jest zwracane niemal od razu.

Z góry dziękuję za odpowiedż.

**Comment by zozlak** [comment]
Baza nie nakłada żadnych limitów na rozmiar pobieranych danych, szybkość ich pobierania ograniczana jest natomiast zasobami sprzętowymi serwera, na którym się znajduje.

Generalnie dopóki zapytanie da się zrealizować w RAM-ie serwera, wszystko działa szybko, a gdy się nie da, gwałtownie zwalnia, choć nadal powinno funkcjonować stabilnie (na bazie dość regularnie realizowane są zapytania zwracające po kilkaset tysięcy rekordów i wykonują się one poprawnie, choć zajmuje to kilkanaście do kilkudziesięciu minut).
Przy tym ilość pamięci potrzebna do zrealizowania zapytania jest mocno powiązana nie tyle z ilością zwracanych rekordów, co z całkowitym rozmiarem przeszukiwanych danych, tym, w jaki sposób są poindeksowane oraz rozmiarami tych indeksów. Gdyby chcieć dokładnie omówić zagadnienie, wyszła by nam książka, więc nie będę wchodził w głębsze szczegóły.

Rady praktyczne, których mogę udzielić:

* Przy bardziej złożonych zapytaniach / pobieraniu większych ilości danych baza może istotnie zwalniać, cały czas powinna jednak działać stabilnie. Proszę spróbować cierpliwie zaczekać, aż skończy (np. zostawić pobieranie na noc).
* Proszę zapoznać się z http://zpd.ibe.edu.pl/doku.php?id=r_wydajnosc

**Comment by zozlak** [comment]
Jeszcze małe post scriptum:

* Baza, do której dostęp ułatwia pakiet ZPD siedzi na serwerze wirtualnym z dwoma rdzeniami i 4 GB RAM-u, tak więc 95% klientów dysponuje mocniejszym sprzętem niż ten serwer.
    * Stąd w celu przyspieszenia przetwarzania danych należy starać się jak najmniej obciążać bazę, a jak najwięcej klienta.
    * Dostępne dla bazy zasoby mogą wydawać się śmiesznie male, ale są, jakie są i większe nie będą. Cieszmy się każdym dniem, w którym IBE je udostępnia (bo w tej chwili robi to jak się zdaje głównie siłą inercji).
