### ISSUE TITLE
Brak możliwości ściągnięcia danych

### ISSUE THREAD

**Issue by psobczyk** [zozlak/ZPD#7]
`library(ZPD)
src = polacz()
szkoly = pobierz_szkoly(src)
s_12 = pobierz_wyniki_egzaminu(src, 'sprawdzian', '', 2012, FALSE)
s_12 = inner_join(s_12, szkoly)
s_12 = s_12 %>% collect()`

Powoduje wywalenia się R. Probówałem też połączyć się bezpośrednio z bazą, ale przykładowe zapytania z widokami również się nie wykonywały.

Moje session info

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    yaml_2.1.14

**Comment by zozlak** [comment]
Problem leży we współpracy pakietu RPostgreSQL z Postgresql-em w wersji 10 (ZPD używa pakietu dplyr, dplyr w dostępie do baz danych polega na DBI, RPostgreSQL jest implementacją DBI dla Postgresql-a, w którym siedzą dane i który został niedawno zaktualizowany do wersji 10).

Niestety na chwilę obecną nie znam żadnego rozwiązania tego problemu (poza debugowaniem pakietu  RPostgreSQL, na co niestety nie mam czasu).

**Comment by psobczyk** [comment]
Ok. Czyli należy użyć starszej wersji RPostgreSQL i powinno śmigać?

**Comment by zozlak** [comment]
Niestety nie. Należy poczekać na nowszą wersję pakietu RPostgresSQL, która będzie poprawnie współpracować z serwerem Postgresql-a w wersji 10.

**Comment by psobczyk** [comment]
Czyli jedyna możliwość dostanie się do danych w tym momencie to odpytanie bezpośrednio bazy? Mam jeszcze pytanie czy istnieje możliwość zadawania pytań o tenże dostęp/uzyskania pomocy? Chciałbym wykonać proste zapytania: wyciągnięcie wyników wybranych egzaminów w kolejnych latach. Nie interesują mnie poszczególne pytania, tylko suma punktów. Połączenie z bazą mam już skonfigurowane

**Comment by zozlak** [comment]
Niestety w tej chwili jedyna możliwość to odpytanie bezpośrednio bazy za pomocą nieR-owego klienta. Z mojego doświadczenia mogę powiedzieć że psql w wersji 10 ("standardowy" konsolowy klient Postgresql-a) pobierał mi dane bez zarzutu.

Pobieranie sumy punktów jest bardziej złożone niż pobranie "surowych" wyników, więc proponuję pobrać całe wyniki, a sumy policzyć sobie później we własnym zakresie.
Zapytanie SQL, które należy wykonać to:
```sql
select zbuduj_widok_egzaminu('mojaNazwaWidoku', 'rodzajEgzaminu', 'czescEgzaminu', rok, czyEwd, czyPunktowac);
select * from "mojaNazwaWidoku";
```
przy czym proszę zwrócić uwagę na podobieństwo funkcji `zbuduj_widok_egzaminu()` do funkcji `pobierz_wyniki_egzaminu()` pakietu ZPD (jedyna różnica to pierwszy parametr, który wewnątrz bazy jest nazwą widoku, który zostanie utworzony, podczas gdy w pakiecie ZPD to obiekt połączenia z bazą danych).

**Comment by tzoltak** [comment]
Można powiedzieć, że pakiet ZPD stał się chwilowo (oby nie na długo) ofiarą decyzji administratora bazy o zostaniu "early adopter" PostgreSQL 10.

**Comment by psobczyk** [comment]
Super, dzięki! Będę testować dzisiaj wieczorem :)

**Comment by zozlak** [comment]
Wydaje się, że problem leżał zupełnie gdzie indziej, a mianowicie:

* po zmigrowaniu bazy do Postgresql-a 10 tablica odpowiedzi została [spartycjonowana](https://www.postgresql.org/docs/10/static/ddl-partitioning.html)
* zapomniałem jednak ustawić praw dostępu do tablic użytych do partycjonowania
* a pakiet RPostgreSQL jest zaimplementowany na tyle kiepsko, że w momencie, gdy baza danych raportowała błąd niedostatecznych uprawnień, RPostgreSQL segfault-ował zamiast elegancko wyświetlić komunikat o błędzie

Poprawiłem prawa dostępu, pobieranie danych powinno ponownie działać.
