### ISSUE TITLE
pobierz_wskazniki(src, doPrezentacji = FALSE)

### ISSUE THREAD

**Issue by tzoltak** [zozlak/ZPD#8]
Wywołanie pobierz_wskazniki() z argumentem doPrezentacji = FALSE zwraca pustą tablicę.

**Comment by zozlak** [comment]
Dzieje się tak dlatego, że filtruje on względem kolumny `do_prezentacji` w tabeli `wskaźniki`, natomiast na sztywno ustawiony jest wymóg wartości `true` dla kolumny `do_prezentacji` w tablicy `sl_wskazniki`.

A jak chcielibyśmy, aby funkcja działała:

* Filtrowała po `do_prezentacji` w tablicy `wskaźniki`, a nie zwracało uwagi na `do_prezentacji` w `sl_wskaniki`?
* Przyjmowała oddzielne parametry dla obydwu tabel?

**Comment by tzoltak** [comment]
Prawdę powiedziawszy skłaniałbym się ku może niezbyt eleganckiemu rozwiązaniu, aby filtrowanie szło po kolumnach z obu tablic. Tzn. jeśli `doPrezentacji = TRUE`, to zwracane są wskaźniki `do_prezentacji` zarówno (jednocześnie) w `sl_wskazniki`  i we `wskazniki`. Z kolei, jeśli `doPrezentacji = FALSE`, to niech by były zwrócone wszystkie, jak leci (bez względu na wartość `do_prezentacji` i w jednej i w drugiej).

**Comment by zozlak** [comment]
Zaimplementowane w 1.7.0

**Comment by tzoltak** [comment]
Miałbym jeszcze jedno pytanie i dwie prośby:

Pytanie i 1. prośba: które `do_prezentacji` zwracane jest przez `pobierz_wskazniki` w kolumnie `wsk_do_prezentacji`? Czy funkcja mogłaby zwracać obie te kolumny z bazy (np. nazywając tą z tablicy `sl_wskazniki` jako "typ_wsk_do_prezentacji")?

2. prośba (była już w wątku powyżej): czy `pobierz_wskazniki(doPrezentacji = FALSE)` mogłoby po prostu zwracać wszystkie wskaźniki jak leci, bez oglądania się na kolumny `do_prezentacji` w bazie? Bo obecnie chcąc uzyskać i jedne i drugie musiałbym wywoływać `pobierz_wskazniki()` dwa razy, a jednocześnie sytuacja, gdy ktoś by chciał mieć dostęp tylko do wskaźników nieprezentowanych wydaje mi się nader rzadka.

**Comment by zozlak** [comment]
ad 2 użyj `doPrezentacji=NA`

**Comment by tzoltak** [comment]
O, fajnie. A mógłbyś to udokumentować?

**Comment by tzoltak** [comment]
A jeszcze ad 1., to może lepiej byłoby nadać kolumnie z tablicy sl_wskazniki nazwę "do_prezentacji_sl" albo "do_prezentacji_sl_wskazniki", bo to będzie bardziej jednoznaczne, niż wprowadzanie przedrostka "typ", który nie wiadomo czym jest i może się mylić z "rodzajem" (EWD vs. PWE).

**Comment by zozlak** [comment]
Zrobione
